#!/usr/bin/env bash
#displays numbers from 1 to 20

t=1
while [ $t -lt 21 ]
do
	case $t in

		4)
			echo $t
			echo "bad luck from China"
			;;

		9)
			echo $t
			echo "bad luck from Japan"
			;;

		17)
			echo $t
			echo "badd luck from Italy"
			;;

		*)
			echo $t
			;;
	esac

	let t+=1
done
